version: "3.3"

services:

  dev-web-server:
    container_name: dev-web-server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PROTOCOL: 2
      PORT: 80
      DEIP_FULL_NODE_URL: http://substrate-node:9933
      DEIP_MONGO_STORAGE_CONNECTION_URL: mongodb://casimir:xZ6GZunKhaUzX44J@storage:27017/casimir-storage?authSource=admin
      CORE_ASSET: '{ "id": 0, "symbol": "DEIP", "precision": 18 }'
      CHAIN_BLOCK_INTERVAL_MILLIS: 6000
      TENANT: "6561845613164402145092105428472817005070"
      TENANT_PRIV_KEY: "1d24d7eda9803457dcea233872d513f4468d41b7a8b77555c161be1d1917330c"
      TENANT_PORTAL: '{"privKey":"1265fe9c39e665908f2d6fda3f0371d34de255e4420eb0aaa2907a8d80836d99","pubKey":"22688b484f3e0dde55bd52221fd9ba806c8af5388e02543e14fbf3a639d4d825"}'
      TENANT_HOT_WALLET: '{"privKey":"38b6bf99e4b06e64cafeeedf1f418f8f03b472e14ece7f5e5cb4d9aa9e6caef7","daoId":"20d1c50067827d1ba447d1be4a4d5129fb0583ed"}'
      TENANT_FILE_STORAGE_TYPE: 1
      QUEUE_SERVICE: kafka
      KAFKA_CLIENT_ID: nft-marketplace-client
      KAFKA_BROKER_URLS: '["kafka:9092"]'
      KAFKA_APP_GROUP_ID: nft-marketplace-app-group
      KAFKA_CHAIN_GROUP_ID: nft-marketplace-chain-group
      KAFKA_APP_TOPIC: nft-marketplace-app-topic
      KAFKA_CHAIN_TOPIC: blockchain
      # KAFKA_USER=my-user
      # KAFKA_PASSWORD=zrQcU3Pux4c9
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - local_casimir_filestorage:/app/files
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver_http.rule=Host(`local.webserver.http.casimir.one`)"
      - "traefik.http.routers.webserver_http.entrypoints=web"
      - "traefik.http.routers.webserver_http.service=webserver_http"
      - "traefik.http.services.webserver_http.loadbalancer.server.port=80"
    networks:
      - local_casimir_nft_marketplace


volumes:
  local_casimir_filestorage:
    external: true


networks:
  local_casimir_nft_marketplace:
    external: true
