version: "3.3"
services:
    deip-server:
        build: .
        container_name: "deip-server"
        restart: always
        environment:
            - NODE_ENV=production
        ports:
            - "80:80"
        links:
            - mongodb
        volumes: 
          - filestorage:/usr/src/app/files
        depends_on:
            - mongodb

    mongodb:
        image: mongo:3.6.5
        container_name: mongodb
        restart: always
        environment:
          - MONGO_INITDB_ROOT_USERNAME=deip
          - MONGO_INITDB_ROOT_PASSWORD=XTFEaoBKqYr
        volumes: 
          - mongostorage:/data/db
        ports:
            - "27017:27017"

networks:  
  default:
    external:
      name: deip

volumes:
  mongostorage:
    external: true
  filestorage:
    external: true
